import { z } from "zod";
import { zColor } from "@remotion/zod-types";

export const factGraphicSchema = z.enum([
  "sleepyCat",
  "earCat",
  "pawTrio",
  "heartCat",
]);

export const factSchema = z.object({
  label: z.string().describe("Badge shown at the top of the scene"),
  caption: z.string().describe("The fact, animated word by word"),
  highlight: z
    .string()
    .describe("Comma-separated words to highlight in the caption"),
  graphic: factGraphicSchema.describe("Vector illustration for this fact"),
  durationInFrames: z.number().min(30).describe("Scene length in frames"),
  bgTop: zColor().describe("Background gradient top color"),
  bgBottom: zColor().describe("Background gradient bottom color"),
  shapeColor: zColor().describe("Floating background shapes color"),
  graphicMain: zColor().describe("Illustration main color"),
  graphicAccent: zColor().describe("Illustration accent color"),
  captionColor: zColor().describe("Caption text color"),
  highlightColor: zColor().describe("Highlighted word text color"),
  highlightBg: zColor().describe("Highlighted word pill color"),
});

export const catFactsSchema = z.object({
  hookTitleTop: z.string().describe("Hook first line"),
  hookTitleBottom: z.string().describe("Hook second line (accent color)"),
  hookSubtitle: z.string().describe("Hook subtitle pill text"),
  hookDurationInFrames: z.number().min(30).describe("Hook scene length"),
  hookBgTop: zColor(),
  hookBgBottom: zColor(),
  hookTitleColor: zColor(),
  hookTitleShadow: zColor().describe("Hard shadow under first title line"),
  hookAccentColor: zColor().describe("Second title line color"),
  hookAccentShadow: zColor().describe("Hard shadow under second title line"),
  hookSubtitleBg: zColor(),
  hookSubtitleColor: zColor(),
  hookCatMain: zColor(),
  hookCatAccent: zColor(),

  facts: z.array(factSchema).describe("The list of did-you-know facts"),

  outroTitle: z.string().describe("Outro big word"),
  outroSubtitle: z.string().describe("Outro subtitle"),
  outroHandle: z.string().describe("Outro handle pill text"),
  outroDurationInFrames: z.number().min(30).describe("Outro scene length"),
  outroBgTop: zColor(),
  outroBgBottom: zColor(),
  outroTitleColor: zColor(),
  outroTitleShadow: zColor(),
  outroSubtitleColor: zColor(),
  outroHandleBg: zColor(),
  outroHandleColor: zColor(),
  outroCatMain: zColor(),
  outroCatAccent: zColor(),
  outroPawColor: zColor().describe("Waving paw color in the outro"),

  captionFontSize: z.number().min(40).describe("Fact caption font size"),
  framesPerWord: z
    .number()
    .min(1)
    .describe("Frames between each caption word appearing"),
  transitionStyle: z.enum([
    "mixed",
    "fade",
    "slide",
    "wipe",
    "clockWipe",
    "flip",
  ]),
  transitionDurationInFrames: z.number().min(1),
});

export type FactProps = z.infer<typeof factSchema>;
export type CatFactsProps = z.infer<typeof catFactsSchema>;

export const catFactsDefaults: CatFactsProps = {
  hookTitleTop: "DID YOU",
  hookTitleBottom: "KNOW?",
  hookSubtitle: "cat facts that sound totally fake",
  hookDurationInFrames: 105,
  hookBgTop: "#8B5CF6",
  hookBgBottom: "#EC4899",
  hookTitleColor: "#FFFFFF",
  hookTitleShadow: "#4C1D95",
  hookAccentColor: "#FDE047",
  hookAccentShadow: "#B45309",
  hookSubtitleBg: "#FFFFFF",
  hookSubtitleColor: "#6D28D9",
  hookCatMain: "#FFB35C",
  hookCatAccent: "#FF8FA3",

  facts: [
    {
      label: "FACT #1",
      caption: "Cats spend 70% of their lives sleeping",
      highlight: "70%",
      graphic: "sleepyCat",
      durationInFrames: 150,
      bgTop: "#38BDF8",
      bgBottom: "#A78BFA",
      shapeColor: "#FFFFFF",
      graphicMain: "#FFB35C",
      graphicAccent: "#FF8FA3",
      captionColor: "#FFFFFF",
      highlightColor: "#FFFFFF",
      highlightBg: "#EC4899",
    },
    {
      label: "FACT #2",
      caption: "A cat's ears can rotate 180° like tiny radar dishes",
      highlight: "180°",
      graphic: "earCat",
      durationInFrames: 150,
      bgTop: "#FBBF24",
      bgBottom: "#FB7185",
      shapeColor: "#FFFFFF",
      graphicMain: "#FFF3E0",
      graphicAccent: "#FF8FA3",
      captionColor: "#FFFFFF",
      highlightColor: "#FFFFFF",
      highlightBg: "#7C3AED",
    },
    {
      label: "FACT #3",
      caption: "A group of kittens is called a kindle",
      highlight: "kindle",
      graphic: "pawTrio",
      durationInFrames: 150,
      bgTop: "#34D399",
      bgBottom: "#A3E635",
      shapeColor: "#FFFFFF",
      graphicMain: "#F472B6",
      graphicAccent: "#FB923C",
      captionColor: "#FFFFFF",
      highlightColor: "#FFFFFF",
      highlightBg: "#7C3AED",
    },
    {
      label: "FACT #4",
      caption: "A cat's purr vibrates at frequencies that can heal bones",
      highlight: "heal bones",
      graphic: "heartCat",
      durationInFrames: 150,
      bgTop: "#F472B6",
      bgBottom: "#818CF8",
      shapeColor: "#FFFFFF",
      graphicMain: "#94A3B8",
      graphicAccent: "#FB7185",
      captionColor: "#FFFFFF",
      highlightColor: "#7C2D12",
      highlightBg: "#FDE047",
    },
  ],

  outroTitle: "FOLLOW",
  outroSubtitle: "for daily cat facts!",
  outroHandle: "@catfacts.daily",
  outroDurationInFrames: 120,
  outroBgTop: "#FB923C",
  outroBgBottom: "#F472B6",
  outroTitleColor: "#FFFFFF",
  outroTitleShadow: "#9D174D",
  outroSubtitleColor: "#FFFFFF",
  outroHandleBg: "#FFFFFF",
  outroHandleColor: "#DB2777",
  outroCatMain: "#FFB35C",
  outroCatAccent: "#FF8FA3",
  outroPawColor: "#FFFFFF",

  captionFontSize: 88,
  framesPerWord: 4,
  transitionStyle: "mixed",
  transitionDurationInFrames: 15,
};
